name: cubaopenplay
description: Application store implemented on the Cuban platform Apklis to promote Cuban open source applications.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  apklis_api: ^0.1.0
  animated_theme_switcher: ^1.0.6
  photo_view: ^0.10.0
  flutter_markdown: ^0.4.3
  html2md: ^0.5.1
  url_launcher: ^5.5.0
  transparent_image: ^1.0.0
  share: ^0.6.4+3
  flutter_bloc: ^6.0.1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  get_it: ^4.0.4
  rxdart: ^0.24.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/cubaopenplay_icon.png"
  image_path_ios: "assets/images/cubaopenplay_icon_ios.png"

flutter_native_splash:
  image: assets/images/cubaopenplay_splash_dark.png
  color: "ffffff"
  fill: true
